name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 1.20.4-zh
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.3.3
      
    - name: Set up JDK 21
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 21

    - name: Maven Build
      run: |
        cd fabric
        chmod +x gradlew
        ./gradlew build
        cd ..
        cd forge
        ./gradlew build

    - name: 自动释放
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "jar"
        prerelease: true
        title: "自动构建版本"
        files: |
          **/build/libs/*.jar
